# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "favicon.ico"
    high_res_favicon: "favicon.ico"
    apple_touch_icon: "favicon.ico"
    keywords: linshine

Intro:
    name: Linshine
    slogan: "Whatever is worth doing is worth doing well <br/> I'll think of you every step of the way"
    HeadButton: Home

Nav:
    Home_name: 主页 
    is_use_categories : false 
    categories_name: 分类
    is_use_archives : false
    archives_name: 归档
    icon:
        github: 
            use: false
            link: 
        Twitter:
            use: false
            link: 
        Facebook:
            use: false
            link: 
        Instagram:
            use: false
            link:
    pages:
        # 图库 :
        #     link: "/gallery/"
        标签:
            link: "/tags/"
        关于: 
            link: "/about/"
        #自定义标签名
        #   link：“路径”

MainFirst:
    name: Linshine
    description: Welcome to my Blog  
    pic_url: /images/me.jpg
    goto_ulr: "/about/"

Gallery :
    title: 游 · 记 
    description: 博学，审问，慎思，明辨，笃行

# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Custom code Render System 自定义代码渲染 
# default dark funky okaidia twilight coy solarized  可选项  
# link to review : http://prismjs.com/index.html   官网预览
prism: coy

# Custom Fonts
fonts: FZLTCXHJW, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "FZLTCXHJW", Arial, sans-serif

# Comment Systems
# Available value of "use":
#     duoshuo | disqus | disqus_click | changyan
comment:
    use: changyan
    shortname: http-miccall-tech 
    duoshuo_thread_key_type: path
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"
    changyan_appid: 'cytoVRn2O'
    changyan_conf: 'prod_8d1d2ca3d3e58602e938a09b0529415d'
    changyan_thread_key_type: path

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: Just another fine responsive  
    

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"
